leo:
  gazebo_ros_control:
    pid_gains:
      wheel_FL_joint:
        p: 1.0
        i: 0.01 
        d: 1.0
      wheel_FR_joint:
        p: 1.0
        i: 0.01 
        d: 1.0
      wheel_RL_joint:
        p: 1.0
        i: 0.01 
        d: 1.0
      wheel_RR_joint:
        p: 1.0
        i: 0.01 
        d: 10
   
   
