wheel_odom_covariance_diagonal: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.001]
imu_angular_velocity_covariance_diagonal: [0.000001, 0.000001, 0.00001]
imu_linear_acceleration_covariance_diagonal: [0.001, 0.001, 0.001]
